### ISSUE TITLE
responseValidationFailed(Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(403))

### ISSUE THREAD

**Issue by drakeson** [cmcgheit/Tube-Playlist#1]
2018-01-22 13:10:51.040311+0300 Tube-Playlist[15203:3090233] [MC] Lazy loading NSBundle MobileCoreServices.framework
2018-01-22 13:10:51.041968+0300 Tube-Playlist[15203:3090233] [MC] Loaded MobileCoreServices.framework
request url: Optional(https://www.googleapis.com/youtube/v3/playlists?channelId=UCYy4nlCUYVOSwWgjUwunFiA&key=AIxxxxxxxxxxx&maxResults=7&part=snippet)
responseValidationFailed(Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(403))

**Comment by cmcgheit** [comment]
@drakeson I apologize, I am just now seeing this issue. That type of error relates to Alamofire and the server/web. If you would like I can chat with you on [Glitter](https://gitter.im) ? I will be closing the issue for now.
